version: "3.6"
services:
  app:
    build: flask_container
    container_name: "Flask_App"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    command: sh -c "/wait && uwsgi app.ini"
    environment:
      - WAIT_HOSTS=redis:6379, db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=2
      - WAIT_HOST_CONNECT_TIMEOUT=30

  db:
    image: mysql:5.7
    container_name: "MySQL_Database"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"